version: "3.9"

services:
  postgres:
    build: database
    restart: always
    container_name: postgres
    command: ["postgres",
              "-c", "logging_collector=on",
              "-c", "log_directory=/var/lib/postgresql/logs",
              "-c", "log_filename=postgres.log",
              "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data
      - ${POSTGRES_LOG}:/var/lib/postgresql/logs

volumes:
  postgres: